# Generated by Django 4.0.2 on 2022-02-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desigination', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
